### ISSUE TITLE
System language settings

### ISSUE THREAD

**Issue by DiSlord** [joeqsmith/NanoVNA_Software#3]
Some users work in different language settings
In it digit separator not '.' as on english language (for example on Russian regional settings this ',')
Software not work vs it.
Need change to '.' but this not good change this parameter for one software.

**Comment by joeqsmith** [comment]
I am not sure what the problem would be.  Obviously there are people in various countries running it.   I assume you read the manual and made the changes from section 10.2 Windows Regional Settings  to the .INI file and it did not correct the problem you are having.  
  
To solve it, I need you to explain in detail what OS you are running, what you are changing and how the software is responding.  From there, I may be able to help.

**Comment by DiSlord** [comment]
I use windows (any varsion)
Some regional settings use different from dot '.'
https://social.msdn.microsoft.com/Forums/en-US/4b59a245-7511-4548-8fdc-25b5e1a2ee60/changing-regional-settings-to-modify-decimal-separator-ssas-2016-tabular?forum=sqlanalysisservices

Try change setting to comma ',' (used for ecample in Russian system settings)
Now software not work (see screenshot, data contain 0)
![1](https://user-images.githubusercontent.com/28828/119868024-304e4e00-bf27-11eb-964d-f98e8cffe698.jpg)

if i change my system regional parameter to dot '.' all work fine.

**Comment by joeqsmith** [comment]
My setup works correctly.  Yours behaves like I would expect if you had not read the manual and followed the instructions.   Please read the following very carefully. 

"I assume you read the manual and made the changes from section 10.2 Windows Regional Settings to the .INI file and it did not correct the problem you are having."

«Я предполагаю, что вы прочитали руководство и внесли изменения из раздела 10.2« Региональные настройки Windows »в файл .INI, и это не устранило вашу проблему».

10.2	Windows Regional Settings

If you have selected regional settings that use a comma rather than decimal point, the software will not communicate with the device.  The first time the software is ran it will create an .INI file.  You will need add useLocaleDecimalPt=False to this file.  The next time the program is executed, it should now use the decimal point.  

10.2 Региональные настройки Windows

Если вы выбрали региональные настройки, в которых используется запятая, а не десятичная точка, программное обеспечение не будет взаимодействовать с устройством. При первом запуске программы создается файл .INI. Вам нужно будет добавить в этот файл useLocaleDecimalPt = False. В следующий раз, когда программа будет выполнена, теперь она должна использовать десятичную точку.

**Comment by joeqsmith** [comment]
Did you make these changes?  If so, did it solve your problem?

**Comment by DiSlord** [comment]
I can`t see any *.ini file in program folder.
It create defaults.set file (in binary format)

**Comment by joeqsmith** [comment]
That .ini file should always be created the first time the software is ran and it should always show up in the directory where the EXE is present.  It will have the same name as the exe.  Maybe you have some odd Windows settings, like hide known file extensions.

**Comment by joeqsmith** [comment]
I wonder when you installed it, if you followed the readme and installed the old software first, then downloaded the new software and copied the EXE over the old one?  My guess is that is where you went wrong.  The INI file is created when running that very first install.  No matter.  You can just create it.  The manual show the contents of the INI file or you can use the following:

[NanoVNA]
server.app.propertiesEnabled=True
server.ole.enabled=True
server.tcp.paranoid=True
server.tcp.serviceName="My Computer/VI Server"
server.vi.callsEnabled=True
server.vi.propertiesEnabled=True
WebServer.TcpAccess="c+*"
WebServer.ViAccess="+*"
DebugServerEnabled=False
DebugServerWaitOnLaunch=False
useLocaleDecimalPt=False

**Comment by joeqsmith** [comment]
https://www.eevblog.com/forum/rf-microwave/nanovna-custom-software/msg3579391/#msg3579391
